version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest discover -s tests/ -p 'test_*.py'
